markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Tao的網誌
url: http://ztpala.com
subscribe: http://feeds.feedburner.com/pala
exclude: [ README.md, newpost.rb ]
domain: ztpala.com
author: Tao Zhang
email: ztpala+blog@gmail.com
auto: true
twitterID: ztpala
googleAnalyticsID: UA-5531632-1